// Generated by CoffeeScript 1.10.0
(function() {
  $.ajaxSetup({
    beforeSend: function(xhr) {
      var ref, xsrf_token;
      xsrf_token = (ref = document.cookie.match("\\b" + name + "=([^;]*)\\b")) != null ? ref[1] : void 0;
      if (xsrf_token) {
        return xhr.setRequestHeader('X-XSRFToken', xsrf_token);
      } else {
        return console.warn("no xsrf token");
      }
    }
  });

  d3.msgpack = function(url, callback) {
    var ref, xhr, xsrf_token;
    xsrf_token = (ref = document.cookie.match("\\b" + name + "=([^;]*)\\b")) != null ? ref[1] : void 0;
    if (!xsrf_token) {
      console.warn("no xsrf token");
    }
    xhr = d3.xhr(url).header('X-XSRFToken', xsrf_token).responseType("arraybuffer").response(function(request) {
      if (request.response.byteLength > 0) {
        return msgpack.decode(request.response);
      } else {
        return "";
      }
    });
    if (callback != null) {
      return xhr.get(callback);
    } else {
      return xhr;
    }
  };

}).call(this);

//# sourceMappingURL=__init__.js.map
