// Generated by CoffeeScript 1.10.0
(function() {
  BL.Framework.ModalStack = (function() {
    function ModalStack() {}

    return ModalStack;

  })();

  BL.Framework.Modal = (function() {
    function Modal() {}

    return Modal;

  })();

}).call(this);

//# sourceMappingURL=Modal.js.map
