// Generated by CoffeeScript 1.10.0
(function() {
  var SubApplication,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  SubApplication = require("../framework/SubApplication.coffee").SubApplication;

  exports.Information = (function(superClass) {
    extend(Information, superClass);

    function Information(pure) {
      this.pure = pure != null ? pure : $("<div id=\"information\" class=\"cell\" style=\"display: none; padding: 0; margin: 0\">\n	<h2>Basic Information</h2>\n	<div class=\"row\"><label>Name:</label><span class=\"attribute\">Brian Peter Ledger</span></div>\n	<div class=\"row\"><label>Birthday:</label><span class=\"attribute\">January 8th, 1988</span></div>\n	<div class=\"row\"><label>Hometown:</label><span class=\"attribute\">Medford, NY</span></div>\n\n	<h2>Contact Information</h2>\n	<div class=\"row\"><label>Email:</label><span class=\"attribute\"><a href=\"mailto:brian.peter.ledger@gmail.com\">brian.peter.ledger@gmail.com</a></span></div>\n	<div class=\"row\"><label>Phone Number:</label><span class=\"attribute\"><a href=\"tel:16314135403\">(631) 413-5403</a></span></div>\n	<div class=\"row\"><label>Current Address:<br/>&zwnj;</label><span class=\"attribute\">126 Day Street<br/>Boston, MA 02130</span></div>\n	<div class=\"row\"><label>Website:</label><span class=\"attribute\"><a href=\"https://brianledger.net\">brianledger.net</a></span></div>\n\n	<h2>Academic Information</h2>\n	<div class=\"row\"><label>College:</label><span class=\"attribute\">Cornell '10</span></div>\n	<div class=\"row\"><label>High School:</label><span class=\"attribute\">Longwood High School ’06</span></div>\n\n	<h2>Personal Information</h2>\n	<div class=\"row\"><label>Activities:</label><span class=\"attribute\">biking, sailing</span></div>\n\n</div>");
      this.get_height = bind(this.get_height, this);
      this.get_width = bind(this.get_width, this);
      this.close = bind(this.close, this);
      this.open = bind(this.open, this);
    }

    Information.prototype.open = function(callback) {
      if (this.pure.css('display') !== "none") {
        return typeof callback === "function" ? callback() : void 0;
      }
      this.pure.css({
        display: "block",
        'max-height': 0,
        'max-width': "1px",
        'border-left': "1px solid gray"
      });
      return this.pure.animate({
        'max-height': this.pure_outer_height || "30rem"
      }, 300, (function(_this) {
        return function() {
          _this.pure.css({
            'border-left': "",
            border: "1px solid gray"
          });
          return _this.pure.animate({
            'max-width': _this.pure_outer_width || "100vw",
            padding: '4px',
            margin: '1px'
          }, 200, function() {
            _this.pure.css({
              'max-width': "",
              'max-height': ""
            });
            return typeof callback === "function" ? callback() : void 0;
          });
        };
      })(this));
    };

    Information.prototype.close = function(callback) {
      if (this.pure.css('display') === "none") {
        return typeof callback === "function" ? callback() : void 0;
      }
      this.pure_outer_height = this.pure.outerHeight();
      this.pure_outer_width = this.pure.outerWidth();
      this.pure.css({
        'max-height': this.pure_outer_height,
        'max-width': this.pure_outer_width
      });
      return this.pure.animate({
        'max-width': "1px",
        margin: 0,
        padding: 0
      }, 300, (function(_this) {
        return function() {
          _this.pure.css({
            border: "none",
            'border-left': "1px solid gray"
          });
          return _this.pure.animate({
            'max-height': 0,
            padding: 0,
            margin: 0
          }, 200, function() {
            _this.pure.css({
              'display': "none",
              'border-left': ""
            });
            return typeof callback === "function" ? callback() : void 0;
          });
        };
      })(this));
    };

    Information.prototype.get_width = function() {
      return this.pure.outerWidth();
    };

    Information.prototype.get_height = function() {
      return this.pure.outerHeight();
    };

    return Information;

  })(SubApplication);

}).call(this);

//# sourceMappingURL=Information.js.map
