// Generated by CoffeeScript 1.10.0
(function() {
  var Request;

  Request = (function() {
    var class1;

    function Request() {
      return class1.apply(this, arguments);
    }

    class1 = (Request.pure = $("<div id=\"request\">\n	<div class=\"info\">\n		\n	</div>\n	<div class=\"actions\">\n		<button id=\"submit-request\">Request Appointment</button>\n	</div>\n</div>"));

    return Request;

  })();

}).call(this);

//# sourceMappingURL=Request.js.map
